apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30080
