apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: testing
spec:
  selector:
    app: api-server
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
  type: ClusterIP


      

